[platformio]
default_envs = xiao_nrf52840_sense

[env:xiao_nrf52840_sense]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-afruitnrf52-nrf52840-sense-plus
framework = arduino
monitor_speed = 115200
lib_archive = no
platform_packages =
  toolchain-gccarmnoneeabi@~1.140201.0
lib_deps =
  seeed-studio/Seeed Arduino LSM6DS3
